(define (problem roverprob1234) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 - Rover
	rover0store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 - Waypoint
	camera0 camera1 - Camera
	objective0 objective1 objective2 - Objective
	; Objetos relacionados a la funcionalidad de bateria
	battery0 battery1 - Battery
    batterylevel0 batterylevel1 batterylevel2 batterylevel3 batterylevel4 batterylevel5 batterylevel6 - Batterylevel
	)
(:init
	(visible waypoint1 waypoint0)
	(visible waypoint0 waypoint1)
	(visible waypoint2 waypoint0)
	(visible waypoint0 waypoint2)
	(visible waypoint2 waypoint1)
	(visible waypoint1 waypoint2)
	(visible waypoint3 waypoint0)
	(visible waypoint0 waypoint3)
	(visible waypoint3 waypoint1)
	(visible waypoint1 waypoint3)
	(visible waypoint3 waypoint2)
	(visible waypoint2 waypoint3)
	(visible waypoint4 waypoint1)
    (visible waypoint1 waypoint4)
	(at_soil_sample waypoint0)
	(at_rock_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_rock_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint3)
	(at_lander general waypoint0)
	(channel_free general)
	(at rover0 waypoint3)
	(at rover1 waypoint2)
	(available rover0)
	(available rover1)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(equipped_for_imaging rover1)
	(can_traverse rover0 waypoint3 waypoint0)
	(can_traverse rover0 waypoint0 waypoint3)
	(can_traverse rover0 waypoint3 waypoint1)
	(can_traverse rover0 waypoint1 waypoint3)
	(can_traverse rover0 waypoint1 waypoint2)
	(can_traverse rover0 waypoint2 waypoint1)
	(can_traverse rover0 waypoint1 waypoint4)
	(can_traverse rover0 waypoint4 waypoint1)
	(can_traverse rover1 waypoint3 waypoint0)
	(can_traverse rover1 waypoint0 waypoint3)
	(can_traverse rover1 waypoint3 waypoint1)
	(can_traverse rover1 waypoint1 waypoint3)
	(can_traverse rover1 waypoint1 waypoint2)
	(can_traverse rover1 waypoint2 waypoint1)
	(on_board camera0 rover0)
    (on_board camera1 rover1)
	(calibration_target camera1 objective1)
    (calibration_target camera0 objective2)
	(supports camera0 colour)
	(supports camera0 high_res)
	(supports camera1 colour)
	(supports camera1 high_res)
	(visible_from objective0 waypoint0)
	(visible_from objective0 waypoint1)
	(visible_from objective0 waypoint2)
	(visible_from objective0 waypoint3)
	(visible_from objective1 waypoint0)
	(visible_from objective1 waypoint1)
	(visible_from objective1 waypoint2)
	(visible_from objective1 waypoint3)
    (visible_from objective2 waypoint4)
	; Estados anteriores de carga de bateria
	(has_battery_left batterylevel5 batterylevel6)
	(has_battery_left batterylevel4 batterylevel5)
	(has_battery_left batterylevel3 batterylevel4)
	(has_battery_left batterylevel2 batterylevel3)
	(has_battery_left batterylevel1 batterylevel2)
	(has_battery_left batterylevel0 batterylevel1)
	; Pone una bateria en un rover
	(on_board_battery battery0 rover0)
	(on_board_battery battery1 rover1)
	; Se configura carga inicial en las baterias
	(at_battery_level battery0 batterylevel6)
	(at_battery_level battery1 batterylevel6)
)

; Para visualizar mejor el funcionamiento de baterias, se coloca un nuevo objetivo
; Este objetivo es que la bateria del primer rover se recarge para una posible nueva mision
(:goal (and
			(communicated_soil_data waypoint2)
			(communicated_rock_data waypoint3)
			(communicated_image_data objective1 high_res)
			(communicated_image_data objective2 high_res)
			(communicated_image_data objective2 colour)
			(at_battery_level battery0 batterylevel6)
		)
	)
)
